server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: movie-service
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

